### ISSUE TITLE
Pets disappear when window is resized

### ISSUE THREAD

**Issue by dimchee** [giusgad/pets.nvim#24]
Sorry for no description, I thought that this bug was general enough.

Whenever I use my Ctrl+Arrow keybinding to tile a kitty window to a side (I use Gnome 43.2),
pets disappear. I am not using kitty as my daily terminal emulator, I use wez, in which pet positioning is wrong all together,
but I suppose that is due to kitty protocol implementation. I use default options for pets, and `popup={winblend=10}` doesn't change anything

**Comment by giusgad** [comment]
This doesn't happen for me, could you please provide more information like what are the options you are using and what commands you run that led to the issue?

**Comment by giusgad** [comment]
Sorry for the delay, the reason I asked you to test with `winblend=10` was to see if the popup disappeared too or the popup stayed in place and only the pet disappeared. This wouldn't work if you use `avoid_statusline=true` in which case you can either unset it or change the highlight group to a background you can see.

If it's the popup's fault, I'm already thinking about how to resize it on window resizes, so it will be probably be fixed when I implement that. Otherwise we will need additional troubleshooting because I cannot reproduce your issue.
