### ISSUE TITLE
Respect to SeethingSwarm wishes and licence

### ISSUE THREAD

**Issue by XanX3601** [giusgad/pets.nvim#25]
Hi ! 
I am very fond of this plugin, maybe one of the greatest plugin of all time while being one of the most useless making it the most required of all.
I do however have a concern about how the sprite sheets of the cats are used because the author, on their website responded that they do not wish for their sprite sheets to be freely accessible. Yet they are freely accessible in this opened source git repository. Isn't that in direct violation of their will and license ?
![image](https://user-images.githubusercontent.com/23431250/221320890-bea25d46-864a-4be5-b24d-b2f377eea51c.png)

**Comment by giusgad** [comment]
I thought a lot about this and had concluded that what the artist meant was that I hadn't to base my plugin on just giving away assets for free. There is also an older question related to open source projects and the artist said it was fine. Additionally I saw that vscode-pets has the media on the repo and i thought it was fine since it is a bigger and more established project. To be sure I reached out to the artist again hoping to receive an okay to my assumptions, I will follow whatever directives they give when they answer.
