### ISSUE TITLE
Not working on WSL

### ISSUE THREAD

**Issue by Svaught598** [giusgad/pets.nvim#38]
### Description

Just installed via lazyvim config on neovim in WSL. `PetsNew helo` does not spawn a pet, and instead displays the message: 

`Not an editor command: PetsNew helo`

### Steps to reproduce

1. Install on LazyVim in WSL
2. try to spawn a pet
3. error

### Your options

```Lua
default options from readme
```

**Comment by giusgad** [comment]
If the command is not registered, I guess there must be something wrong with the installation and/or calling the setup function. If those are done correctly there is probably some kind of issue with wsl, I never used it so I don't really know if it can cause problems. I think it's really unlikely that this is a bug in the plugin because if you call the setup function there is no way the commands don't get registered... 
Maybe try reinstalling or calling the setup function explicitly without using lazy's options table. Also test if commands from other plugins work, because if they don't it's probably a more general problem

**Comment by Svaught598** [comment]
Yep, I'll close this. It was not being called correctly in my configuration, and the docs are pretty clear that this doesn't work without a terminal like kitty, so it didn't work for me regardless. It would be sweet if the graphics backend was more generic so it would work on the default WSL shell, but I'm sure that's a ton of work.
